version: 0.2
phases:
  build:
    yum:
      java-21-amazon-corretto: [ ]
    commands:
      - echo Packaging JAR file...
      - mvn clean package
  post_build:
    commands:
      - echo Build complete.
artifacts:
  files:
    - target/BookStore.jar
  discard-paths: yes