version: 4- 1
phases:
  install:
  build:
    commands:
      - export JAVA_HOME="/usr/lib/jvm/java-21-amazon-corretto"
      - export PATH=$JAVA_HOME/bin:$PATH
      - echo Packaging JAR file...
      - mvn clean package
  post_build:
    commands:
      - echo Build complete.
artifacts:
  files:
    - target/BookStore.jar
  discard-paths: yes