version: 0.2
phases:
  build:
    install:
      runtime-versions:
        java: 21
    commands:
      - echo Packaging JAR file...
      - mvn clean package
  post_build:
    commands:
      - echo Build complete.
artifacts:
  files:
    - target/BookStore.jar
  discard-paths: yes