package com.bookstore.models;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonIgnore;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Digits;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

/**
 * Class for Book details
 */
public class BookModel {
	/**
	 * This will be filled by service. So no need of validation
	 */
	@Schema
	private String bookId; // id is auto generated

	@NotNull(message = "Name is a required field")
	@Size(min = 1, max = 50, message = "Book name must be between 1 and 50 characters")
	private String name;

	@NotNull(message = "Author name is a required field")
	@Size(min = 1, max = 50, message = "Author name must be between 1 and 50 characters")
	private String author;

	@NotNull(message = "Publish date is a required field")
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date publishDate;

	@NotNull(message = "Description is a required field")
	@Size(min = 1, max = 2000, message = "Description must be between 1 and 2000 characters")
	private String description;

	@NotNull(message = "Price is a required field")
	@Digits(fraction = 2, integer = 10, message = "Price only accepts upto 10 digits and 2 fraction; like 50.25")
	private float price;

	@NotNull(message = "Quantity is a required field")
	@Digits(fraction = 0, integer = 10, message = "Quantity only accepts upto 10 digits")
	private int quantity;

	/**
	 * This will be filled by service. So no need of validation
	 */
	@Schema(hidden = true)
	@JsonIgnore
	private String owner; // user who listed the book

	/**
	 * Default constructor for spring boot model
	 */
	public BookModel() {
		this.publishDate = new Date();
	}

	

	/**
	 * Create a book model object
	 * @param bookId      unique book id auto generated by service
	 * @param name        name / title
	 * @param author      author
	 * @param publishDate publish date
	 * @param description description
	 * @param price       cost
	 * @param quantity    number available
	 * @param owner       user listed book
	 */
	public BookModel(String bookId, String name, String author, Date publishDate, String description, float price,
			int quantity, String owner) {
		super();
		this.bookId = bookId;
		this.name = name;
		this.author = author;
		this.publishDate = publishDate;
		this.description = description;
		this.price = price;
		this.quantity = quantity;
		this.owner = owner;
	}

	/**
	 * book id
	 * @return id
	 */
	public String getBookId() {
		return this.bookId;
	}

	/**
	 * set book id
	 * @param id id
	 */
	public void setBookId(String id) {
		this.bookId = id;
	}

	/**
	 * get name 
	 * @return name
	 */
	public String getName() {
		return name;
	}

	/**
	 * set book name
	 * @param name name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * get author
	 * @return author
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * set author
	 * @param author author
	 */
	public void setAuthor(String author) {
		this.author = author;
	}

	/**
	 * date published
	 * @return date
	 */
	public Date getPublishDate() {
		return publishDate;
	}

	/**
	 * set date published
	 * @param publishDate date
	 */
	public void setPublishDate(Date publishDate) {
		this.publishDate = publishDate;
	}

	/**
	 * get description
	 * @return description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * set description
	 * @param description desc
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * get price
	 * @return price
	 */
	public float getPrice() {
		return price;
	}

	/**
	 * set price
	 * @param price price
	 */
	public void setPrice(float price) {
		this.price = price;
	}

	/**
	 * get quantity
	 * @return quantity
	 */
	public int getQuantity() {
		return quantity;
	}

	/**
	 * set quantity
	 * @param quantity quantity
	 */
	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	/**
	 * owner of the book
	 * @return owner
	 */
	public String getOwner() {
		return owner;
	}

	/**
	 * Set owner of the book
	 * @param owner owner
	 */
	public void setOwner(String owner) {
		this.owner = owner;
	}
}
